## library() calls go here
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("between", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("slice", "dplyr")
conflict_prefer("pluck", "purrr")
conflict_prefer("chisq.test", "stats")
conflict_prefer("fisher.test", "stats")
conflict_prefer("map", "purrr")
conflict_prefer("pull", "dplyr")
conflict_prefer("complete", "tidyr")
conflict_prefer("expand", "tidyr")

library(conmat)
library(cowplot)
library(dotenv)
library(distributional)
library(fs)
library(glue)
library(here)
library(janitor)
library(knitr)
library(lubridate)
library(patchwork)
library(pscl)
library(readr)
library(readxl)
library(rmarkdown)
library(scales)
library(stats)
library(stickylabeller)
library(targets)
library(tarchetypes)
library(testthat)
library(truncdist)
library(tidyverse)
library(vctrs)
library(RColorBrewer)
library(tinter)
library(future.apply)

message("packages loaded!")