## library() calls go here
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("slice", "dplyr")
conflict_prefer("pluck", "purrr")
conflict_prefer("chisq.test", "stats")
conflict_prefer("fisher.test", "stats")
conflict_prefer("map", "purrr")
conflict_prefer("binomial", "greta")
conflict_prefer("poisson", "greta")
conflict_prefer("colMeans", "greta")
conflict_prefer("apply", "greta")
conflict_prefer("%*%", "greta")
conflict_prefer("pull", "dplyr")
conflict_prefer("complete", "tidyr")
conflict_prefer("expand", "tidyr")

library(dotenv)
library(fs)
library(glue)
library(grid)
library(greta, warn.conflicts = FALSE)
library(greta.gp, warn.conflicts = FALSE)
library(here)
library(janitor)
library(knitr)
library(lubridate)
library(lme4)
library(mgcv)
library(patchwork)
library(R6)
library(RColorBrewer)
library(readr)
library(readxl)
library(reticulate)
library(rjson)
library(rmarkdown)
library(rvest)
library(scales)
library(sf)
library(slider)
library(splines)
library(stats)
library(tensorflow)
library(targets)
library(tarchetypes)
library(truncdist)
library(tidyverse)
library(truncdist)
library(units)
library(vctrs)
library(zip)


message("packages loaded!")