---
title: "Untitled Draft"
author: "Report Author"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    keep_md: true
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.height=10,
  fig.width = 10,
  dev = "png",
  dpi = 300
  )
## target knits Rmds in their own session, so load libraries here.
## source("here::here(packages.R"))
```

```{r load-targets, include=FALSE}
# tar_load(c(target_1, target_2, target_3))

# # If your chunk output is shown in-line, then you'll need to wrap tar_load()
# # like so:
# 
withr::with_dir(here::here(), {
  tar_load(
    c(
      cases_nsw,
      scenario_vaccination_isolation,
      scenario_run_vaccination_isolation,
      cases_nsw_delays,
      cases_vic_delays,
      cases_scenario,
      cases_nsw_interview_missings,
      derived_delay_distributions,
      delay_dist_funs,
      delay_samples,
      scenario_df,
      scenario_df_run,
      scenario_df_run_tp_multiplier,
      cases_nsw_delays_long,
      cases_nsw_raw_delay_long,
      are_cases_independent,
      delay_samples_against_data,
      prepared_cases_for_plots,
      plot_scenario_vaccination_isolation,
      plot_hist_delay_samples_v_data,
      plot_tp_reduction,
      scenario_df_run_plots,
      experiment_plots
      )
    )
})
# 
# # This is not needed when using tar_make() to render the document.
```


```{r}
derived_delay_distributions
```


## EDA

```{r}
cases_nsw_delays_long <- cases_delay_longer(cases_nsw_delays)
cases_vic_delays_long <- cases_delay_longer(cases_vic_delays)
```

```{r gg-cases-delays-cases-nsw-raw-delay-long}
gg_cases_delays(cases_nsw_delays_long)
```


```{r gg-cases-delays-cases-vic-raw-delay-long}
gg_cases_delays(cases_vic_delays_long)
```


```{r gg-interview-missings-cases-nsw-delays}
gg_interview_missings(cases_nsw_delays)
```


```{r gg-interview-missings-cases-vic-delays}
gg_interview_missings(cases_vic_delays)
```


```{r check-cases-independence-cases-nsw-delays}
check_cases_independence(cases_nsw_delays)
```


```{r check-cases-independence-cases-vic-delays}
check_cases_independence(cases_vic_delays)
```


```{r gg-cases-nsw-delays-cases-nsw-delays-long}
gg_cases_nsw_delays(cases_nsw_delays_long)
```


```{r gg-cases-nsw-delays-cases-vic-delays-long}
gg_cases_nsw_delays(cases_vic_delays_long)
```


```{r}
# cases_vic_raw_delay_long %>% 
#     group_by(delay_type) %>% 
#     count(days, sort = TRUE) %>% 
#     mutate(prop = n / sum(n))
#   
#   
#     ggplot(aes(x = days)) + 
#     geom_histogram(binwidth = 1) + 
#     facet_wrap(~delay_type)
```


```{r}
# scenario_df_run_tp_multiplier %>% 
#   relocate(time_to_isolation_sims,
#            sim_tracing_fun,
#            .after = tp_multiplier)  %>% 
#   mutate(tti_sims = map())
```

## Figures

```{r plot-hist-nsw-delay-samples-v-data}
plot_hist_delay_samples_v_data
```

```{r plot-nsw-tp-reduction}
plot_tp_reduction
```

## Analysis

```{r show-trace-run}
scenario_df_run 
```

```{r}
  cases_scenario %>% 
    group_by(scenario) %>% 
    summarise(
      across(
        .cols = c(
          test_turnaround_time,
          time_to_interview,
          full_contact_delay
          ),
        .fns = mean,
        na.rm = TRUE
        )
    )

  cases_scenario %>%
    select(test_turnaround_time,
           time_to_interview,
           full_contact_delay,
           scenario) %>% 
    pivot_longer(
      cols = -scenario,
      names_to = "delay_type",
      values_to = "days"
    ) %>% 
    ggplot(aes(x = days)) +
    geom_bar() + 
    facet_grid(scenario~delay_type)
  
```

## Queueing orders {.tabset .tabset-pills}

```{r, echo=FALSE}
# Construct chunks for each LPHU plot/table
out = lapply(names(experiment_plots), function(x) {
  paste0(
    paste0("### ", x, "\n"),          # Section title
    paste0("```{r ", x %>% str_replace("\\.", "_"), ", echo=FALSE}\n"),   # Chunk header
    paste0("experiment_plots$`", x, "`\n"),       # Chunk content
    "```\n",                          # End chunk
    collapse="\n") # Assemble code
})
```

`r paste(knitr::knit(text = paste(out, collapse="\n")))`

## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
